import { Inject,Injectable } from '@nestjs/common';
import { PrismaService } from '../../../database/prisma.service';
import { AuditService } from '../../../platform/audit/audit.service';
import { ApiError } from '../../../common/http/api-error';
import { normalizeHumanName,normalizeKey } from '@custom-school/validation';
import type { SessionActor,StudentsPublicFacade } from '@custom-school/contracts';
import { STUDENTS_PUBLIC_FACADE } from '../students-port/students.port';

@Injectable()
export class AcademicsService {
  constructor(private readonly prisma:PrismaService,private readonly audit:AuditService,@Inject(STUDENTS_PUBLIC_FACADE)private readonly students:StudentsPublicFacade){}
  private async schoolExists(id:string){const s=await this.prisma.school.findUnique({where:{id},select:{id:true}});if(!s)throw new ApiError(404,'ERR_SCHOOL_NOT_FOUND','School not found');}
  async listClasses(schoolId:string){await this.schoolExists(schoolId);return this.prisma.class.findMany({where:{schoolId},orderBy:[{sortOrder:'asc'},{name:'asc'}],include:{sections:{orderBy:[{sortOrder:'asc'},{name:'asc'}]}}});}
  async createClass(actor:SessionActor,schoolId:string,input:any){await this.schoolExists(schoolId);try{return await this.prisma.$transaction(async tx=>{const row=await tx.class.create({data:{schoolId,name:normalizeHumanName(input.name),normalizedName:normalizeKey(input.name),sortOrder:input.sortOrder||0}});await this.audit.append({requestId:actor.requestId,schoolId,actorType:'PLATFORM_ADMIN',actorId:actor.userId,eventType:'CLASS_CREATED',targetType:'CLASS',targetId:row.id,metadata:{name:row.name,sortOrder:row.sortOrder}},tx as any);return row;});}catch(e:any){if(e?.code==='P2002')throw new ApiError(409,'ERR_CLASS_DUPLICATE','Class name already exists');throw e;}}
  async updateClass(actor:SessionActor,schoolId:string,classId:string,input:any){return this.prisma.$transaction(async tx=>{await (tx as any).$queryRaw`SELECT id FROM classes WHERE school_id=${schoolId}::uuid AND id=${classId}::uuid FOR UPDATE`;const current=await tx.class.findFirst({where:{id:classId,schoolId}});if(!current)throw new ApiError(404,'ERR_CLASS_NOT_FOUND','Class not found');const data:any={};if(input.name!==undefined){data.name=normalizeHumanName(input.name);data.normalizedName=normalizeKey(input.name);}if(input.sortOrder!==undefined)data.sortOrder=input.sortOrder;if(input.status!==undefined)data.status=input.status;try{const row=await tx.class.update({where:{id:classId},data});await this.audit.append({requestId:actor.requestId,schoolId,actorType:'PLATFORM_ADMIN',actorId:actor.userId,eventType:'CLASS_UPDATED',targetType:'CLASS',targetId:classId,metadata:{fields:Object.keys(input)}},tx as any);return row;}catch(e:any){if(e?.code==='P2002')throw new ApiError(409,'ERR_CLASS_DUPLICATE','Class name already exists');throw e;}});}
  async deleteClass(actor:SessionActor,schoolId:string,classId:string){return this.prisma.$transaction(async tx=>{await (tx as any).$queryRaw`SELECT id FROM classes WHERE school_id=${schoolId}::uuid AND id=${classId}::uuid FOR UPDATE`;const current=await tx.class.findFirst({where:{id:classId,schoolId}});if(!current)throw new ApiError(404,'ERR_CLASS_NOT_FOUND','Class not found');const active=await this.students.countActiveEnrollment({schoolId,classId});if(active>0)throw new ApiError(409,'ERR_ACADEMIC_IN_USE','Class has active student enrollments');const sections=await tx.section.count({where:{schoolId,classId}});if(sections>0)throw new ApiError(409,'ERR_CLASS_HAS_SECTIONS','Remove or deactivate sections before destructive delete');await tx.class.delete({where:{id:classId}});await this.audit.append({requestId:actor.requestId,schoolId,actorType:'PLATFORM_ADMIN',actorId:actor.userId,eventType:'CLASS_DELETED',targetType:'CLASS',targetId:classId},tx as any);});}
  async createSection(actor:SessionActor,schoolId:string,classId:string,input:any){return this.prisma.$transaction(async tx=>{await (tx as any).$queryRaw`SELECT id FROM classes WHERE school_id=${schoolId}::uuid AND id=${classId}::uuid FOR SHARE`;const parent=await tx.class.findFirst({where:{id:classId,schoolId}});if(!parent)throw new ApiError(404,'ERR_CLASS_NOT_FOUND','Class not found');try{const row=await tx.section.create({data:{schoolId,classId,name:normalizeHumanName(input.name),normalizedName:normalizeKey(input.name),sortOrder:input.sortOrder||0}});await this.audit.append({requestId:actor.requestId,schoolId,actorType:'PLATFORM_ADMIN',actorId:actor.userId,eventType:'SECTION_CREATED',targetType:'SECTION',targetId:row.id,metadata:{classId,name:row.name}},tx as any);return row;}catch(e:any){if(e?.code==='P2002')throw new ApiError(409,'ERR_SECTION_DUPLICATE','Section name already exists in this class');throw e;}});}
  async updateSection(actor:SessionActor,schoolId:string,classId:string,sectionId:string,input:any){return this.prisma.$transaction(async tx=>{await (tx as any).$queryRaw`SELECT id FROM sections WHERE school_id=${schoolId}::uuid AND class_id=${classId}::uuid AND id=${sectionId}::uuid FOR UPDATE`;const current=await tx.section.findFirst({where:{id:sectionId,schoolId,classId}});if(!current)throw new ApiError(404,'ERR_SECTION_NOT_FOUND','Section not found');const data:any={};if(input.name!==undefined){data.name=normalizeHumanName(input.name);data.normalizedName=normalizeKey(input.name);}if(input.sortOrder!==undefined)data.sortOrder=input.sortOrder;if(input.status!==undefined)data.status=input.status;try{const row=await tx.section.update({where:{id:sectionId},data});await this.audit.append({requestId:actor.requestId,schoolId,actorType:'PLATFORM_ADMIN',actorId:actor.userId,eventType:'SECTION_UPDATED',targetType:'SECTION',targetId:sectionId,metadata:{fields:Object.keys(input)}},tx as any);return row;}catch(e:any){if(e?.code==='P2002')throw new ApiError(409,'ERR_SECTION_DUPLICATE','Section name already exists in this class');throw e;}});}
  async deleteSection(actor:SessionActor,schoolId:string,classId:string,sectionId:string){return this.prisma.$transaction(async tx=>{await (tx as any).$queryRaw`SELECT id FROM sections WHERE school_id=${schoolId}::uuid AND class_id=${classId}::uuid AND id=${sectionId}::uuid FOR UPDATE`;const current=await tx.section.findFirst({where:{id:sectionId,schoolId,classId}});if(!current)throw new ApiError(404,'ERR_SECTION_NOT_FOUND','Section not found');const active=await this.students.countActiveEnrollment({schoolId,sectionId});if(active>0)throw new ApiError(409,'ERR_ACADEMIC_IN_USE','Section has active student enrollments');await tx.section.delete({where:{id:sectionId}});await this.audit.append({requestId:actor.requestId,schoolId,actorType:'PLATFORM_ADMIN',actorId:actor.userId,eventType:'SECTION_DELETED',targetType:'SECTION',targetId:sectionId},tx as any);});}
}
