export const DASHBOARD_STUDENTS_FACADE = 'DASHBOARD_STUDENTS_FACADE';
export const DASHBOARD_FEES_FACADE = 'DASHBOARD_FEES_FACADE';
export const DASHBOARD_TRANSPORT_FACADE = 'DASHBOARD_TRANSPORT_FACADE';
